"""add request channel and config release

Revision ID: 2bf2c3bf8d12
Revises: ff0f8df77ce0
Create Date: 2026-10-09 12:05:34.591991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bf2c3bf8d12'
down_revision: Union[str, Sequence[str], None] = 'ff0f8df77ce0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('request_channel', sa.String(), nullable=False))
    op.add_column('requests', sa.Column('config_release_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'config_release_id')
    op.drop_column('requests', 'request_channel')
    # ### end Alembic commands ###
