"""create requests table

Revision ID: ff0f8df77ce0
Revises: 
Create Date: 2026-10-08 13:28:22.821681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff0f8df77ce0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('message_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('accepted_business_message_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('attachment_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('use_case_id', sa.String(), nullable=True),
    sa.Column('use_case_history', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('active_clarification', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('clarification_history', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('closure_reason', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('support_handoff_reference', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('request_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requests')
    # ### end Alembic commands ###
