from enum import Enum


class MessageType(str, Enum):
    HUMAN_AGENT_REQUEST = "HUMAN_AGENT_REQUEST"
    ACTIONABLE_CONTEXTUAL = "ACTIONABLE_CONTEXTUAL"
    COMMUNICATION_ONLY = "COMMUNICATION_ONLY"